import type { MasterDataListSortOption } from '@/components/MasterDataListToolbar'
import {
  buildMasterDataColumns,
  type MasterDataColumn,
  withMasterDataDefaults,
} from '@/lib/master-data-columns'
import { ITEM_FORM_FIELDS } from '@/lib/item-form-customization'
import { ID_NEWEST_OLDEST_NAME_SORT_OPTIONS } from '@/lib/record-list-sort'

export type MasterDataListDefinition = {
  columns: MasterDataColumn[]
  searchPlaceholder: string
  tableId: string
  exportFileName: string
  sortOptions: MasterDataListSortOption[]
  compactExport?: boolean
}

export const currencyListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'currency-id', label: 'Currency Id' },
    { id: 'code', label: 'Code' },
    { id: 'name', label: 'Name' },
    { id: 'symbol', label: 'Symbol' },
    { id: 'decimals', label: 'Decimals' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created', defaultVisible: false },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search Currency Id, code, or name',
  tableId: 'currencies-list',
  exportFileName: 'currencies',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const locationListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'location-id', label: 'Location Id' },
    { id: 'code', label: 'Code' },
    { id: 'name', label: 'Name' },
    { id: 'subsidiary', label: 'Subsidiary' },
    { id: 'parent-location', label: 'Parent Location' },
    { id: 'location-type', label: 'Location Type' },
    { id: 'make-inventory-available', label: 'Make Inventory Available' },
    { id: 'address', label: 'Address' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created', defaultVisible: false },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search Location Id, code, name, subsidiary, type, or address',
  tableId: 'locations-list',
  exportFileName: 'locations',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const accountingPeriodListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'name', label: 'Name' },
    { id: 'start-date', label: 'Start Date' },
    { id: 'end-date', label: 'End Date' },
    { id: 'subsidiary', label: 'Subsidiary' },
    { id: 'status', label: 'Status' },
    { id: 'closed', label: 'Closed' },
    { id: 'ar-locked', label: 'AR Locked' },
    { id: 'ap-locked', label: 'AP Locked' },
    { id: 'inventory-locked', label: 'Inventory Locked' },
    { id: 'closed-at', label: 'Closed At' },
    { id: 'created', label: 'Created', defaultVisible: false },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search accounting period name, status, or subsidiary',
  tableId: 'accounting-periods-list',
  exportFileName: 'accounting_periods',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const managedListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'list-key', label: 'List Key' },
    { id: 'list-name', label: 'Name' },
    { id: 'where-used', label: 'Where Used' },
    { id: 'values', label: 'Values' },
    { id: 'display-order', label: 'Display Order' },
    { id: 'type', label: 'Type' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search list key, name, or where used',
  tableId: 'managed-lists-list',
  exportFileName: 'managed_lists',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const priceLevelListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'price-level-id', label: 'Price Level Id' },
    { id: 'name', label: 'Name' },
    { id: 'level-type', label: 'Level Type' },
    { id: 'subsidiary', label: 'Subsidiary' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'default-discount', label: 'Default Discount %' },
    { id: 'minimum-margin', label: 'Minimum Margin %' },
    { id: 'approval-required', label: 'Approval Required' },
    { id: 'allow-manual-override', label: 'Allow Manual Override' },
    { id: 'effective-start', label: 'Effective Start' },
    { id: 'effective-end', label: 'Effective End' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'db-id', label: 'DB Id', defaultVisible: false },
    { id: 'created', label: 'Created', defaultVisible: false },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search Price Level Id, name, type, or subsidiary',
  tableId: 'price-levels-list',
  exportFileName: 'price_levels',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const priceBookListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'price-book-id', label: 'Price Book Id' },
    { id: 'name', label: 'Name' },
    { id: 'book-type', label: 'Book Type' },
    { id: 'subsidiary', label: 'Subsidiary' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'currency', label: 'Currency' },
    { id: 'default-price-level', label: 'Default Price Level' },
    { id: 'approval-required', label: 'Approval Required' },
    { id: 'allow-manual-override', label: 'Allow Manual Override' },
    { id: 'effective-start', label: 'Effective Start' },
    { id: 'effective-end', label: 'Effective End' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'db-id', label: 'DB Id', defaultVisible: false },
    { id: 'created', label: 'Created', defaultVisible: false },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search Price Book Id, name, type, subsidiary, or currency',
  tableId: 'price-books-list',
  exportFileName: 'price_books',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const itemListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'itemId', label: 'Item Id', defaultVisible: true },
    { id: 'name', label: 'Name', defaultVisible: true },
    ...ITEM_FORM_FIELDS.filter((field) => field.id !== 'itemId' && field.id !== 'name').map((field) => ({
      id: field.id,
      label: field.id === 'defaultRevRecTemplateId' ? 'Rev Rec Template' : field.label,
      defaultVisible: [
        'sku',
        'itemType',
        'listPrice',
        'subsidiaryIds',
        'currencyId',
        'itemCategory',
        'revenueStream',
        'incomeAccountId',
        'standardCost',
        'directRevenuePosting',
      ].includes(field.id),
    })),
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search name, Item Id, SKU',
  tableId: 'items-list',
  exportFileName: 'items',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const chartOfAccountsListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'account-id', label: 'Account Id', locked: true },
    { id: 'account-number', label: 'Account Number', locked: true },
    { id: 'name', label: 'Name' },
    { id: 'description', label: 'Description' },
    { id: 'type', label: 'Account Type' },
    { id: 'account-category', label: 'Account Category' },
    { id: 'normal-balance', label: 'Normal Balance' },
    { id: 'fs-section', label: 'FS Section' },
    { id: 'fs-group', label: 'FS Group' },
    { id: 'fs-category', label: 'FS Category' },
    { id: 'account-role', label: 'Account Role' },
    { id: 'rollforward-category', label: 'Rollforward Category' },
    { id: 'parent-account', label: 'Parent Account' },
    { id: 'posting', label: 'Posting' },
    { id: 'control', label: 'Control' },
    { id: 'inventory', label: 'Inventory' },
    { id: 'revalue-open-balance', label: 'Remeasure Open Balance' },
    { id: 'monetary-classification', label: 'Monetary Classification' },
    { id: 'translation-treatment', label: 'Translation Treatment' },
    { id: 'summary', label: 'Summary' },
    { id: 'subsidiaries', label: 'Subsidiaries' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'active', label: 'Active' },
    { id: 'db-id', label: 'DB Id', defaultVisible: false },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified', defaultVisible: false },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search Account Id, Account Number, name, type, or role',
  tableId: 'chart-of-accounts-list',
  exportFileName: 'chart_of_accounts',
  sortOptions: [
    { value: 'id', label: 'Id' },
    { value: 'newest', label: 'Newest' },
    { value: 'oldest', label: 'Oldest' },
    { value: 'name', label: 'Name A-Z' },
  ],
}

export const departmentListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'department-id', label: 'Department Id' },
    { id: 'department-number', label: 'Department Number' },
    { id: 'name', label: 'Name' },
    { id: 'description', label: 'Description' },
    { id: 'division', label: 'Division' },
    { id: 'subsidiaries', label: 'Subsidiaries' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'planning-category', label: 'Planning Category' },
    { id: 'manager', label: 'Manager' },
    { id: 'approver', label: 'Approver' },
    { id: 'status', label: 'Inactive' },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search Department Id, Department Number, name, description, or division',
  tableId: 'departments-list',
  exportFileName: 'departments',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const departmentColumnLabels: Record<string, string> = {
  'department-id': 'Department Id',
  'department-number': 'Department Number',
  name: 'Name',
  description: 'Description',
  division: 'Division',
  subsidiaries: 'Subsidiaries',
  'include-children': 'Include Children',
  'planning-category': 'Planning Category',
  manager: 'Manager',
  approver: 'Approver',
  status: 'Inactive',
  created: 'Created',
  'last-modified': 'Last Modified',
  actions: 'Actions',
}

export const subsidiaryListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'subsidiary-id', label: 'Subsidiary Id' },
    { id: 'name', label: 'Name' },
    { id: 'country', label: 'Country' },
    { id: 'address', label: 'Address' },
    { id: 'tax-id', label: 'Tax ID' },
    { id: 'parent-subsidiary', label: 'Parent Subsidiary' },
    { id: 'legal-name', label: 'Legal Name' },
    { id: 'type', label: 'Type' },
      { id: 'default-currency', label: 'Local Currency' },
      { id: 'functional-currency', label: 'Functional Currency' },
      { id: 'reporting-currency', label: 'Group Currency' },
      { id: 'fiscal-calendar', label: 'Fiscal Calendar', defaultVisible: false },
      { id: 'accounting-standard', label: 'Accounting Standard', defaultVisible: false },
      { id: 'consolidation-method', label: 'Consolidation Method' },
      { id: 'ownership-percent', label: 'Ownership %' },
      { id: 'direct-ownership-percent', label: 'Direct Ownership %', defaultVisible: false },
      { id: 'ultimate-ownership-percent', label: 'Ultimate Ownership %', defaultVisible: false },
      { id: 'ownership-effective-from', label: 'Ownership From', defaultVisible: false },
      { id: 'ownership-effective-through', label: 'Ownership Through', defaultVisible: false },
      { id: 'consolidation-effective-from', label: 'Consolidation From', defaultVisible: false },
      { id: 'consolidation-effective-through', label: 'Consolidation Through', defaultVisible: false },
      { id: 'control-indicator', label: 'Control', defaultVisible: false },
      { id: 'nci-required', label: 'NCI Required', defaultVisible: false },
      { id: 'elimination-target-parent', label: 'Elimination Target Parent', defaultVisible: false },
      { id: 'elimination-scope', label: 'Elimination Scope', defaultVisible: false },
      { id: 'elimination-currency-basis', label: 'Elimination Currency Basis', defaultVisible: false },
      { id: 'retained-earnings-account', label: 'Retained Earnings Account', defaultVisible: false },
      { id: 'cta-account', label: 'CTA Account', defaultVisible: false },
      { id: 'intercompany-clearing-account', label: 'Intercompany Clearing Account', defaultVisible: false },
      { id: 'due-to-account', label: 'Due To Account', defaultVisible: false },
      { id: 'due-from-account', label: 'Due From Account', defaultVisible: false },
      { id: 'investment-in-subsidiary-account', label: 'Investment In Subsidiary Account', defaultVisible: false },
      { id: 'nci-equity-account', label: 'NCI Equity Account', defaultVisible: false },
      { id: 'nci-income-statement-account', label: 'NCI Income Statement Account', defaultVisible: false },
      { id: 'realized-fx-gain-account', label: 'Realized FX Gain Account', defaultVisible: false },
      { id: 'realized-fx-loss-account', label: 'Realized FX Loss Account', defaultVisible: false },
      { id: 'unrealized-fx-gain-account', label: 'Unrealized FX Gain Account', defaultVisible: false },
      { id: 'unrealized-fx-loss-account', label: 'Unrealized FX Loss Account', defaultVisible: false },
      { id: 'allow-transactions', label: 'Allow Transactions', defaultVisible: false },
      { id: 'allow-bank-accounts', label: 'Allow Bank Accounts', defaultVisible: false },
      { id: 'allow-inventory', label: 'Allow Inventory', defaultVisible: false },
      { id: 'allow-payroll', label: 'Allow Payroll', defaultVisible: false },
      { id: 'allow-projects', label: 'Allow Projects', defaultVisible: false },
      { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search subsidiary id or name',
  tableId: 'subsidiaries-list',
  exportFileName: 'subsidiaries',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
  compactExport: true,
}

export const employeeListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'employee-id', label: 'Employee Id' },
    { id: 'eid', label: 'EID' },
    { id: 'name', label: 'Name' },
    { id: 'email', label: 'Email' },
    { id: 'title', label: 'Title' },
    { id: 'labor-type', label: 'Labor Type' },
    { id: 'department', label: 'Department' },
    { id: 'subsidiaries', label: 'Subsidiaries' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'linked-user', label: 'Linked User' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search employee id, EID, name or email',
  tableId: 'employees-list',
  exportFileName: 'employees',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const userListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'id', label: 'User ID' },
    { id: 'name', label: 'Name' },
    { id: 'email', label: 'Email' },
    { id: 'role', label: 'Role' },
    { id: 'department', label: 'Department' },
    { id: 'default-subsidiary', label: 'Default Subsidiary' },
    { id: 'subsidiaries', label: 'Subsidiaries' },
    { id: 'include-children', label: 'Include Children' },
    { id: 'approval-limit', label: 'Approval Limit', defaultVisible: false },
    { id: 'delegated-approver', label: 'Delegated Approver', defaultVisible: false },
    { id: 'locked', label: 'Locked', defaultVisible: false },
    { id: 'employee', label: 'Linked Employee' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'role.name', label: 'Role Name', defaultVisible: false },
    { id: 'department.name', label: 'Department Name', defaultVisible: false },
    { id: 'department.departmentId', label: 'Department ID', defaultVisible: false },
    { id: 'defaultSubsidiary.subsidiaryId', label: 'Default Subsidiary ID', defaultVisible: false },
    { id: 'approvalCurrency.code', label: 'Approval Currency Code', defaultVisible: false },
    { id: 'delegatedApprover.name', label: 'Delegated Approver Name', defaultVisible: false },
    { id: 'delegatedApprover.email', label: 'Delegated Approver Email', defaultVisible: false },
    { id: 'linkedEmployee.employeeId', label: 'Linked Employee ID', defaultVisible: false },
    { id: 'linkedEmployee.lastName', label: 'Linked Employee Last Name', defaultVisible: false },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search user #, name, email, role, or subsidiary',
  tableId: 'users-list',
  exportFileName: 'users',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const roleListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'role-id', label: 'Role Id' },
    { id: 'name', label: 'Name' },
    { id: 'description', label: 'Description' },
    { id: 'users', label: 'Users' },
    { id: 'inactive-users', label: 'Inactive Users' },
    { id: 'active-users', label: 'Active Users' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search role',
  tableId: 'roles-list',
  exportFileName: 'roles',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const contactListDefinition: MasterDataListDefinition = {
  columns: buildMasterDataColumns({
    idColumnId: 'contact-number',
    idLabel: 'Contact Id',
    extraColumns: [
      { id: 'account-type', label: 'Account Type' },
      { id: 'account', label: 'Account' },
      { id: 'email', label: 'Email' },
      { id: 'phone', label: 'Phone' },
      { id: 'address', label: 'Address' },
      { id: 'position', label: 'Position' },
    ],
    includeActionsColumn: true,
  }),
  searchPlaceholder: 'Search contact ID, name, customer, vendor, email, phone',
  tableId: 'contacts-list',
  exportFileName: 'contacts',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const customerListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'number', label: 'Customer Id' },
    { id: 'name', label: 'Name' },
    { id: 'customer-status', label: 'Status' },
    { id: 'customer-type', label: 'Type' },
    { id: 'customer-group', label: 'Group' },
    { id: 'territory', label: 'Territory' },
    { id: 'sales-manager', label: 'Sales Manager' },
    { id: 'subsidiary', label: 'Primary Subsidiary' },
    { id: 'currency', label: 'Primary Currency' },
    { id: 'ar-account', label: 'AR Account' },
    { id: 'reminder-days', label: 'Reminder Days' },
    { id: 'price-level', label: 'Price Level' },
    { id: 'price-book', label: 'Price Book' },
    { id: 'taxable', label: 'Taxable' },
    { id: 'tax-item', label: 'Tax Code' },
    { id: 'collections-rep', label: 'Collections Rep' },
    { id: 'industry', label: 'Industry' },
    { id: 'address', label: 'Billing Address' },
    { id: 'email', label: 'Email' },
    { id: 'phone', label: 'Phone' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'db-id', label: 'DB Id', defaultVisible: false },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search customer #, name, email, territory, manager, status',
  tableId: 'customers-list',
  exportFileName: 'customers',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const billingScheduleListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'billingScheduleId', label: 'Billing Schedule ID' },
    { id: 'name', label: 'Name' },
    { id: 'scheduleType', label: 'Schedule Type' },
    { id: 'frequency', label: 'Frequency' },
    { id: 'billingTiming', label: 'Billing Timing' },
    { id: 'billingAnchor', label: 'Billing Anchor' },
    { id: 'prorationPolicy', label: 'Proration Policy' },
    { id: 'renewalMode', label: 'Renewal Mode' },
    { id: 'invoiceGroupingPolicy', label: 'Invoice Grouping Policy' },
    { id: 'currencyId', label: 'Currency' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'createdAt', label: 'Created' },
    { id: 'updatedAt', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search billing schedule id, name, type, frequency, or policy',
  tableId: 'billing-schedules-list',
  exportFileName: 'billing_schedules',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const billingAccountListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'billingAccountId', label: 'Billing Account ID' },
    { id: 'name', label: 'Name' },
    { id: 'customerId', label: 'Customer' },
    { id: 'accountType', label: 'Account Type' },
    { id: 'status', label: 'Status' },
    { id: 'subsidiaryId', label: 'Subsidiary' },
    { id: 'currencyId', label: 'Currency' },
    { id: 'defaultBillingScheduleId', label: 'Default Billing Schedule' },
    { id: 'defaultPriceBookId', label: 'Default Price Book' },
    { id: 'invoiceDeliveryMethod', label: 'Invoice Delivery' },
    { id: 'paymentTerms', label: 'Payment Terms' },
    { id: 'paymentMethod', label: 'Payment Method' },
    { id: 'taxable', label: 'Taxable' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'createdAt', label: 'Created' },
    { id: 'updatedAt', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search billing account id, name, customer, email, or status',
  tableId: 'billing-accounts-list',
  exportFileName: 'billing_accounts',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const subscriptionPlanListDefinition: MasterDataListDefinition = {
  columns: withMasterDataDefaults([
    { id: 'subscriptionPlanId', label: 'Subscription Plan ID' },
    { id: 'name', label: 'Name' },
    { id: 'planType', label: 'Plan Type' },
    { id: 'billingModel', label: 'Billing Model' },
    { id: 'status', label: 'Status' },
    { id: 'itemId', label: 'Item' },
    { id: 'subsidiaryId', label: 'Subsidiary' },
    { id: 'currencyId', label: 'Currency' },
    { id: 'defaultBillingScheduleId', label: 'Default Billing Schedule' },
    { id: 'defaultPriceBookId', label: 'Default Price Book' },
    { id: 'termMonths', label: 'Term Months' },
    { id: 'autoRenew', label: 'Auto Renew' },
    { id: 'revenueRecognitionPolicy', label: 'Revenue Recognition Policy' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'createdAt', label: 'Created' },
    { id: 'updatedAt', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ]),
  searchPlaceholder: 'Search plan id, name, item, billing model, or status',
  tableId: 'subscription-plans-list',
  exportFileName: 'subscription_plans',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}

export const vendorListDefinition: MasterDataListDefinition = {
  columns: [
    { id: 'vendor-number', label: 'Vendor Id' },
    { id: 'name', label: 'Name' },
    { id: 'subsidiary', label: 'Primary Subsidiary' },
    { id: 'currency', label: 'Primary Currency' },
    { id: 'email', label: 'Email' },
    { id: 'phone', label: 'Phone' },
    { id: 'address', label: 'Address' },
    { id: 'tax-id', label: 'Tax ID' },
    { id: 'inactive', label: 'Inactive' },
    { id: 'created', label: 'Created' },
    { id: 'last-modified', label: 'Last Modified' },
    { id: 'actions', label: 'Actions', locked: true },
  ],
  searchPlaceholder: 'Search vendor id, name, email, phone, tax id',
  tableId: 'vendors-list',
  exportFileName: 'vendors',
  sortOptions: ID_NEWEST_OLDEST_NAME_SORT_OPTIONS,
}
